title: 玲珑少年

author:
  location: 上海
  motto:
    - Away from home,
    - away from home,
    - Lord,
    - I'm 500 miles away from home.

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-lunr-js-search

github_username: auaa

permalink: pretty
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"

timezone: Asia/Shanghai